### ISSUE TITLE
[Backend] UHE TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by gramscih** [DMGochoa/final_prog102#16]
I had an Error trying to execute the backend service, once I execute `python api.py` and return the following exception.
```
Traceback (most recent call last):
  File "/home/ghermozo/Documents/proj102/final_prog102/backend/api.py", line 122, in <module>
    SetupDatabase.setup()
  File "/home/ghermozo/Documents/proj102/final_prog102/backend/setup_db.py", line 93, in setup
    self.create_transaction_table_query()
TypeError: 'str' object is not callable
```

**Comment by lauMv** [comment]
solved in the next commit
