### ISSUE TITLE
[UI Web] UHE FileNotFoundError

### ISSUE THREAD

**Issue by gramscih** [DMGochoa/final_prog102#20]
Trying to execute the UI Web in a clean environment I got the following exception

`Traceback (most recent call last):
  File "/home/ghermozo/Documents/proj102/final_prog102/UI_web/main.py", line 10, in <module>
    from pages.register import register_layout
  File "/home/ghermozo/Documents/proj102/final_prog102/UI_web/pages/register.py", line 17, in <module>
    logger = log_web()
  File "/home/ghermozo/Documents/proj102/final_prog102/UI_web/utils/logging_web.py", line 7, in __init__
    self.__config()
  File "/home/ghermozo/Documents/proj102/final_prog102/UI_web/utils/logging_web.py", line 12, in __config
    logging.basicConfig(
  File "/usr/lib/python3.10/logging/__init__.py", line 2040, in basicConfig
    h = FileHandler(filename, mode,
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/ghermozo/Documents/proj102/final_prog102/UI_web/UI_web/log/basic.log'`

**Comment by DMGochoa** [comment]
With the new PR the path problem is fixed
